apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: airflowplus
  name: airflowplus
  namespace: airflowplus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflowplus
  template:
    metadata:
      labels:
        app: airflowplus
    spec:
      containers:
      - name: docker-airflow
        image: puckel/docker-airflow:latest
      - name: redis
        image: redis:latest
      - name: postgres
        image: postgres:latest
        env:
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
        - name: POSTGRES_PASSWORD
          value: password